name: webview_flutter_web_example
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webview_flutter_web:
    # When depending on this package from a real application you should use:
    #   webview_flutter_web: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  espresso: ^0.1.0+2
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true
